### ISSUE TITLE
Accept button text isn't visible on Terms and Condition page

### ISSUE THREAD

**Issue by kashifali007** [SuperNETorg/Iguana-application#26] opened 2016-12-21 19:18 UTC
Accept button text isn't visible on Terms and Condition page due to which its very hard to judge the purpose of that button. 

**Steps to reproduce:**

1. Make sure atleast one coind is running
2. Navigate to folder where index.html exits and open it in any browser
3. Click on create wallet button
4. copy the passphrase text
5. Enter the passphrase when its asked 
6. here you will be asked for term and condition agreement. on agreement page we can clearly see decline button but its hard to judge accept button due to similar font color of background color

Snapshot is attached for your perusal.
![accept](https://cloud.githubusercontent.com/assets/16662663/21402833/25d60d88-c7dc-11e6-9f95-fa2467c30c56.png)

Please let me know, if you need more detail

Thanks,
-Kashif Ali

**Comment by ed888** [comment] 2016-12-27 14:00
@kashifali007 @imboogieman 
I have tested both on Google Chrome and Mozilla Firefox and couldn't reproduce the bug 
http://i.prntscr.com/c17149750897404087b182ceaf0638a1.png  http://i.prntscr.com/6ebc735926dc4468bfe0f2e4ecf7a07c.png

Can you please test it again and inform me whether this is actual or not?
If it is please give me more details.

**Comment by pbca26** [comment] 2017-01-10 12:42
looks fine
closing the issue

**Closed as completed** 2017-01-10 12:42 UTC
Labels: bug
