### ISSUE TITLE
Stuck at "Authentication error" message box

### ISSUE THREAD

**Issue by pbca26** [SuperNETorg/Iguana-application#55] opened 2017-01-26 19:35 UTC
To reproduce:
- login in iguana mode
- add coin(s)
- wait for some time
- logout
- (optionally) refresh page
- try to login again

Despite clicking on "Log out" the message box comes back again.

@ed888 I see similar issue in iguana electron app if I logout running Iguana mode. Sometimes it's just appearing second time after logging out. This is a serious blocker, please fix it ASAP!

**Comment by pbca26** [comment] 2017-01-26 19:37
![auth-error](https://cloud.githubusercontent.com/assets/7769879/22347134/d0eee422-e417-11e6-9c61-4013155702d7.png)

@ed888 check the screenshot, I selected what Iguana responses back. My guess is that it's all related to the recent auth error issue I mentioned on Slack channel.

**Comment by ed888** [comment] 2017-01-27 08:27
@pbca26 done, please check

**Comment by ed888** [comment] 2017-01-27 08:31
@pbca26 but the problem is that after closing the browser the session is removed and then when the same user opens the browser new authorization key isn't accepted by add coin method on Iguana
what do you think if I update the authorization key each time on Add Coin.

**Comment by pbca26** [comment] 2017-01-27 09:40
@ed888 sure

**Comment by ed888** [comment] 2017-01-27 12:36
@pbca26 I think there should be some modifications in the Iguana core as it doesn't accept the new session key. can you please take care of this? 
once the changes are applied I will do the corresponding changes in the gui.

**Comment by ed888** [comment] 2017-01-27 13:13
@jl777 Can you please take a look at my last mentioned case?

**Comment by pbca26** [comment] 2017-01-30 22:18
Quick update: after conversation w/ james and grewal I added sessionstorage/localstorage switch if gui is running in electron app. This seems to fix auth error issue in iguana app but "plain gui" is left behind. The only solution is to keep auth key in localstorage and reuse it until iguana core is running. Not the best options security wise but there're no other workarounds in this case.

**Comment by ed888** [comment] 2017-01-31 07:18
@pbca26 done, please check

**Comment by pbca26** [comment] 2017-01-31 19:13
@ed888 better.

Couple issues:
1) Iguana Core is not a coin daemon. We need to change wording to something "looks like Iguana Core is not running". @imboogieman can you suggest?
2) @ed888 try to stop iguana core and observe several issues. During dashboard update the message box tends to flicker on the screen. Sometimes the message box just disappears completely even though Iguana Core is not running. These issues are inconsistent but need to be taken care of.
3) If I stop and restart Iguana Core I get "...iguana crashed..." message and it's also flickering during dashboard updates. Can you get rid of it? Make the box stay on the screen w/o flickering until user will hit the logout link.

**Comment by pbca26** [comment] 2017-02-01 17:30
@ed888 can you specify here in a comment which of 3 points have you covered so far?

**Comment by ed888** [comment] 2017-02-02 07:47
@pbca26 I have changed the message showing method. Now for the next message it doesn't open a new modal, simply the text is changed. With my last commit I completed the above mentioned 3 points.

**Comment by ed888** [comment] 2017-02-06 10:23
@pbca26 done, please check

**Closed as completed** 2017-02-07 22:01 UTC
