### ISSUE TITLE
"Passphrase is copied..." wrong message popup

### ISSUE THREAD

**Issue by imboogieman** [SuperNETorg/Iguana-application#51] opened 2017-01-25 21:30 UTC
**Wrong:**
Given I see a generate passphrase
When I highlight any symbol
or I click on the card with the passphrase
Then I see a message "Passphrase copied to clipboard "and all of the words for the passphrase""

![passphrase is copied wrong message popup](https://cloud.githubusercontent.com/assets/16269033/22309911/5d4a1ea6-e35e-11e6-8950-172f213a457e.png)

**Right:**
No message for any action upon passphrase words. Probably mixed with address copy feature.

![receiving_coins_01_2_web 1](https://cloud.githubusercontent.com/assets/16269033/22309948/817dfac2-e35e-11e6-8b26-ef7240bfe522.png)

**Comment by ed888** [comment] 2017-01-26 08:22
@imboogieman Done, please check

**Comment by imboogieman** [comment] 2017-01-27 16:29
@ed888 
Remains.

**Wrong:**
...
When I select the passphrase with the cursor
Or I click on the passphrase form
Then I see the message "Passphrase copied to clipboard"
And the value is saved to clipboard
And I can not call out an OS dialogue windows to apply "Copy" function (Ctrl+C is not working too I believe)

**Right:**
...
When I select the passphrase with the cursor
Then It is highlighted
And I can copy it and save to clipboard:
by Ctrl+C command
by calling out an OS dialogue windows to apply "Copy" function

**Comment by pbca26** [comment] 2017-01-28 09:52
@imboogieman both issues should be fixed. Please verify.

**Comment by ed888** [comment] 2017-01-30 13:31
@imboogieman I tested this one, seems that @pbca26 fixed it. please check and close this ticket as well

**Comment by imboogieman** [comment] 2017-02-01 00:39
@ed888 @pbca26 it remains at my side. 
I uninstalled Iguana and deleted all the files related from Iguana App and Roaming Folders, and it both the message pops up. pls check.

**Comment by ed888** [comment] 2017-02-01 07:12
@imboogieman I cannot reproduce the issue.
@pbca26 May this be because of the gulp ran issue? Am i right?

**Comment by pbca26** [comment] 2017-02-01 07:25
@imboogieman 
>i uninstalled Iguana

please, name all steps that you've taken after that

**Comment by imboogieman** [comment] 2017-02-01 12:35
@pbca26 
1. I deleted the folder IguanaApp
2. I deleted Iguana related files form C:\Users\User\AppData\Roaming
3. I downloaded the exe from the repo. 
4. I installed the app.
5. Changed the files in C:\Users\User\IguanaApp\resources\app\gui\Iguana-GUI for new ones
6. I opened the app
7. I press "create"
8. I clicked on the passphrase generated

**Comment by imboogieman** [comment] 2017-02-02 11:37
@pbca26 @ed888 
Now running Iguana and open index.html in the browser, and it remains. 

![passphrase is copied wrong message popup_01](https://cloud.githubusercontent.com/assets/16269033/22547933/23880ef6-e955-11e6-81b8-f98de56e6572.png)

**Closed as completed** 2017-02-03 11:20 UTC
